---
---
@import "{{ site.theme }}";

body {
  background-image: url("{{ '/assets/background.png' | relative_url }}");
  background-size: cover;
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
}
